Repository CESNET/perun-proxy-api, pull requests merged in 2020-09, with the labels that each got.

#23 getEntitlements method
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/FacadeUtils.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/RelyingPartyFacade.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/RelyingPartyService.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/ServiceUtils.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/RelyingPartyServiceImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/AdapterUtils.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/FullAdapter.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/exceptions/InternalErrorException.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/RelyingPartyProtectedController.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: waiting_for_review

#42 findByIdentifiers API method
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/FacadeUtils.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: new_features, waiting_for_review

#41 Fixed fetching RPC name from mapping in LDAP adapter
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
Labels: waiting_for_review

#43 Fixes in LDAP adapter
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
Labels: bugfix, enhancement

#44 Rest layer documentation + improvements
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/RelyingPartyProtectedController.java
Labels: documentation, enhancement, waiting_for_review

#45 Facade and REST should return UserDTO
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
Labels: bugfix, enhancement, waiting_for_review

#40 Refactored Attribute and AttributeValue
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapper.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/enums/AttributeType.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/models/AttributeObjectMapping.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttribute.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeDefinition.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeValue.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeValueAwareModel.java
Labels: waiting_for_review

#46 Fetch login for users
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/AdapterUtils.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapper.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/models/User.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
Labels: enhancement, waiting_for_review

#50 Exception resolver for REST
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/RelyingPartyFacade.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/connectors/PerunConnectorRpc.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/exceptions/EntityNotFoundException.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/exceptions/InternalErrorException.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/exceptions/InvalidNumberOfValuesException.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/ExceptionResolver.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/RelyingPartyProtectedController.java
Labels: enhancement, new_features, waiting_for_review

#27 Proxy user tests
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttribute.java
  src/test/java/cz/muni/ics/perunproxyapi/TestUtils.java
  src/test/java/cz/muni/ics/perunproxyapi/application/facade/ProxyUserFacadeTest.java
  src/test/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserServiceTest.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImplTest.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImplTestUserRelated.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/VoTests.java
  src/test/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedControllerTest.java
  src/test/resources/application.yml
  src/test/resources/configs/attributes.yml
Labels: merge_soon
