Repository CESNET/perun-proxy-api, pull requests merged in 2020-10, with the labels that each got.

#64 Tests for models
  src/main/java/cz/muni/ics/perunproxyapi/persistence/models/UpdateAttributeMappingEntry.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/AttributeObjectMappingTests.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/ExtSourceTests.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/FacilityTests.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/GroupTests.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/MemberTests.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeTests.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeValueTests.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/ResourceTests.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/UpdateAttributeMappingEntryTests.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/UserExtSourceTests.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/models/UserTests.java
Labels: merge_soon, needs_changes

#65 Tests for RPC user related adapter methods
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
  src/test/java/cz/muni/ics/perunproxyapi/TestUtils.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImplUserRelatedTest.java
  src/test/resources/configs/proxyuser-facade.yml
Labels: merge_soon, needs_changes

#66 ga4gh
  openapi.yml
  pom.xml
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/FacadeUtils.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
  src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/Ga4ghBeans.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/Ga4ghImplType.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/JWKSetPublishingEndpoint.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/JWTSigningAndValidationService.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/model/ActiveClaimRepository.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/model/ClaimRepository.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/model/Ga4ghProperties.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/model/JWKSetKeyStore.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/model/PassportVisa.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/model/Signer.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/model/config/ElixirGa4ghConfig.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/service/Ga4ghService.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/service/impl/ElixirGa4ghService.java
  src/main/java/cz/muni/ics/perunproxyapi/ga4gh/service/impl/UnsupportedGa4ghService.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/FullAdapter.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/exceptions/MissingOrInvalidFileException.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/models/Affiliation.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttribute.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/config/WebSecurityConfiguration.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
  src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/interceptors/AddHeaderInterceptor.java
  src/main/resources/application.yml
  src/test/java/cz/muni/ics/perunproxyapi/application/facade/ProxyUserFacadeTest.java
  src/test/resources/application.yml
  src/test/resources/configs/ga4gh.yml
Labels: waiting_for_review

#68 Tests for mappers
  src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapper.java
  src/main/java/cz/muni/ics/perunproxyapi/persistence/exceptions/MissingFieldException.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImplUserRelatedTest.java
  src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapperTest.java
Labels: do_not_merge_yet, needs_changes
